apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesrv
  namespace: kubesrv-ns
  labels:
    app: kubesrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubesrv
  template:
    metadata:
      labels:
        app: kubesrv
    spec:
      containers:
        - name: kubesrv
          image: bansikah/kubesrv:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: kubesrv-cm
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
  